### ISSUE TITLE
Error with voter match: changing voter name mid-search results in mixed up status on dash

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#12]
So, this is a bit complex, but follow me.

I added a contact, "Peter" "Frayling" "Overland Park"

I searched for a match, could not find one, did all I could, could not find him, maybe he's unregistered. So there in the search box, I changed the search terms to look for "Brian" "Becker" "Olathe" and found him, and indicated "This is them".

All good. His info in the dashboard looks great. I know that was a thing you worked on, pulling their matched info to replace the original contact info, so good. But when I click on the green "Registered?" status, it pops up with the name still las "Peter Frayling" So just some clean-up, I guess. Sorry I did not catch this one earlier.

Here's a screenshot:

<img width="1011" alt="screen shot 2018-05-29 at 12 35 31 pm" src="https://user-images.githubusercontent.com/38695722/40675266-e23ec094-633c-11e8-822a-8467677c356b.png">

**Comment by MainStreamDanny** [comment]
More follow up, this also affects the alphabetical ordering in the Dashboard. So Becker is after Fisher because Becker is being alphabetized as Frayling. FYI.

**Comment by MainStreamDanny** [comment]
Also, when disconnecting the voter from the voter file, it reverts to whatever you entered when you created the contact. I get there might become value in keeping the name someone entered as the contact (I know him as "Danny" Novo, even if his file is under "Robert") but it's not clear enough that this is the behavior, and it doesn't account for people where I just made am mistake (like "Sarah" for Sara Aitken). So I think the path of least resistance is to blow away the originally entered Contact name when a contact is matched successfully, and replace it with the matched name. IMHO.

**Comment by jakelowen** [comment]
Let's define a common parlance so we can discuss with precision here..

When a user adds a new contact, they provide first name, last name, city.  For the sake of clarity lets call those UP_firstname, UP_lastname etc (up = user provided)

When a user matches a record to the voter file we now have linked record information.  Lets call that LR_firstname etc (LR = Linked voter file record)

So...  as it stands now, a person definitely has a UP_* info, but only has LR_* if matched.  IF LR_* is present, it will over-ride and display that instead of UP_* info.  If a record is not matched we only have UP_*

I hesitate to ever overwrite the UP_* info for one big reason: Imagine you add a new contact, "John Doe". You then search the file and ACCIDENTALLY link the record with a very wrong name like  "Jonah Doebermankavich".  You immediately realize your mistake and then unlink the record so you can start over again.  If the UP_* info is overwritten at the time of linking with the selected LR_* info, you would then need to go back and edit the UP_* fields back to how you know the person. I could imagine a scenario where an ambassador has dozens of contacts added, and doesn't catch a linking error until after the fact. Now they realize, "wait a second, I don't know anyone named Jonah Doebermankavich" and then can't remember who that was supposed to be in the first place.

In my mind its best to maintain separate UP and LR info for that reason.   In your screenshot above I would read that to say "The contact you created with the name Peter Frayling has been linked to voter file record with the name Brian Becker - If this is not a correct linkage, remove the association by clicking the red button below and find a better match for Brian Becker".

Perhaps this is more an area of needing better copy writing / instructions instead. Thoughts?

I agree there is an issue with the alphabetization based on UP last name. We can address that, but lets make sure we have agreement on above.

**Comment by MainStreamDanny** [comment]
Okay, yes, I see the value in keeping the data integrity stream. Your example of Doebermankavich is excellent. So let's not overwrite the UP_data with LR_data.

Clearly, we should alphabetize by LR_lastname, if present.

And my use case for problems, where I am looking for Brian Becker but switch, in the search interface, to looking for Lori Levens then match her, is on me, the user. It could be confusing for a user who does not realize/remember that's what they did.

I think an excellent solution is your suggestion of the following text on the "Associated Voter File Record" dialog, except with the UP_name in the last sentence: "The contact you created with the name UP_firstname UP_lastname has been linked to voter file record with the name LR_firstname LR_lastname - If this is not a correct linkage, remove the association by clicking the red button below and find a better match for UP_firstname UP_lastname."

It's wordy, but I'd rather wordy and clear to concise and not clear. So do that and call it good.

**Comment by MainStreamDanny** [comment]
Just for reflection, in an alternate timeline, I like the idea of letting people name their contacts how they like, "Danny Novo" and when matched, list them as "Danny Novo (Robert Novo)" or something. That would require enabling the Edit button for UP_data after they have been matched (right now it is hidden, per my request, I believe). Not a big priority. I'll open an issue for it, but feel free to label it "later" (I still haven't figured out how to label things here in Git).
