### ISSUE TITLE
Dashboard flickers out of existence

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#18]
Also, the dashboard page now loads briefly as a flicker then winks out of existence, replaced by a blank white screen.

The source says I need to enable javascript... but I'm pretty sure I haven't made any changes since yesterday.

<img width="801" alt="screen shot 2018-05-31 at 11 17 05 am" src="https://user-images.githubusercontent.com/38695722/40794255-400d30c4-64c4-11e8-8392-31b05fe0b48b.png">

**Comment by MainStreamDanny** [comment]
Yeah, that's not it. If I disable javascript in the developer tools, then I get that message on my screen. But with javascript enabled, I just get the flicker and a blank screen.

**Comment by jakelowen** [comment]
Weird. No idea there. I'm thinking / hoping it was a tiny glitch related to the deploy process. Just as you filed that issue I was currently deploying a new version. Part of that deploy is to stand up a new app container, switch over traffic and then delete the previous version one.  Maybe you got caught somewhere in that transition?  Going to close this because I can not recreate, but please reopen if it happens again.

BTW.. new deployed version is live with all of this morning's revisions.
