### ISSUE TITLE
Tried to delete an organization, in Postico, failed

### ISSUE THREAD

**Issue by MainStreamDanny** [gpsimpact/mainstream_relational_gotv#30]
So, was trying to delete Danny's Test Org from the organizations table (for the training), and it won't let me because it violates a rule, probably some sort of dependency. I deleted myself from the permissions table. Still can't. Help?

**Comment by jakelowen** [comment]
That delete probably failed because a row in another table was depending on it and deleting that row would break the dependency.  A very quick review shows that permissions and potential_voters tables both have foreign key dependencies to orgs tables.

So if you want to delete an org, make sure that org has no associated permissions or potential_voters.

If you get sick of doing all that by hand, that is what the CASCADE argument in SQL queries are for..   DELETE FROM organizations WHERE id = '....'  CASCADE.  The cascade argument also then deletes and dependencies.. but of course be very careful when deleting data via query. If you ommitted the `WHERE id = '....'` it would delete every org, every permission and every contact!
